export const RETRIEVE_HAULER_LIST_REQUEST = 'RETRIEVE_HAULER_LIST_REQUEST'
export const RETRIEVE_HAULER_LIST_SUCCESS = 'RETRIEVE_HAULER_LIST_SUCCESS'
export const RETRIEVE_HAULER_LIST_FAIL = 'RETRIEVE_HAULER_LIST_FAIL'

export const RETRIEVE_HAULER_SCHEDULE_PICKUP_REQUEST = 'RETRIEVE_HAULER_SCHEDULE_PICKUP_REQUEST'
export const RETRIEVE_HAULER_SCHEDULE_PICKUP_SUCCESS = 'RETRIEVE_HAULER_SCHEDULE_PICKUP_SUCCESS'
export const RETRIEVE_HAULER_SCHEDULE_PICKUP_FAIL = 'RETRIEVE_HAULER_SCHEDULE_PICKUP_FAIL'

export const RETRIEVE_HAULER_SPECIAL_PICKUP_REQUEST = 'RETRIEVE_HAULER_SPECIAL_PICKUP_REQUEST'
export const RETRIEVE_HAULER_SPECIAL_PICKUP_SUCCESS = 'RETRIEVE_HAULER_SPECIAL_PICKUP_SUCCESS'
export const RETRIEVE_HAULER_SPECIAL_PICKUP_FAIL = 'RETRIEVE_HAULER_SPECIAL_PICKUP_FAIL'

export const HAULER_ADD_REQUEST = 'HAULER_ADD_REQUEST'
export const HAULER_ADD_SUCCESS = 'HAULER_ADD_SUCCESS'
export const HAULER_ADD_FAIL = 'HAULER_ADD_FAIL'
export const HAULER_ADD_RESET = 'HAULER_ADD_RESET'

export const HAULER_DELETE_SUCCESS = 'HAULER_DELETE_SUCCESS'
export const HAULER_DELETE_FAIL = 'HAULER_DELETE_FAIL'
export const HAULER_DELETE_RESET = 'HAULER_DELETE_RESET'

export const HAULER_DETAIL_UPDATE_REQUEST = 'HAULER_DETAIL_UPDATE_REQUEST'
export const HAULER_DETAIL_UPDATE_SUCCESS = 'HAULER_DETAIL_UPDATE_SUCCESS'
export const HAULER_DETAIL_UPDATE_FAIL = 'HAULER_DETAIL_UPDATE_FAIL'
export const HAULER_DETAIL_UPDATE_RESET = 'HAULER_DETAIL_UPDATE_RESET'

export const RETRIEVE_HAULER_DETAIL_REQUEST = 'RETRIEVE_HAULER_DETAIL_REQUEST'
export const RETRIEVE_HAULER_DETAIL_SUCCESS = 'RETRIEVE_HAULER_DETAIL_SUCCESS'
export const RETRIEVE_HAULER_DETAIL_FAIL = 'RETRIEVE_HAULER_DETAIL_FAIL'