export const RETRIEVE_HAULER_LIST_REQUEST = 'RETRIEVE_HAULER_LIST_REQUEST'
export const RETRIEVE_HAULER_LIST_SUCCESS = 'RETRIEVE_HAULER_LIST_SUCCESS'
export const RETRIEVE_HAULER_LIST_FAIL = 'RETRIEVE_HAULER_LIST_FAIL'

export const HAULER_ADD_REQUEST = 'HAULER_ADD_REQUEST'
export const HAULER_ADD_SUCCESS = 'HAULER_ADD_SUCCESS'
export const HAULER_ADD_FAIL = 'HAULER_ADD_FAIL'