export const RETRIEVE_HAULER_LIST_REQUEST = 'RETRIEVE_HAULER_LIST_REQUEST'
export const RETRIEVE_HAULER_LIST_SUCCESS = 'RETRIEVE_HAULER_LIST_SUCCESS'
export const RETRIEVE_HAULER_LIST_FAIL = 'RETRIEVE_HAULER_LIST_FAIL'