export const RETRIEVE_SCHEDULE_PICKUP_LIST_REQUEST = 'RETRIEVE_SCHEDULE_PICKUP_LIST_REQUEST'
export const RETRIEVE_SCHEDULE_PICKUP_LIST_SUCCESS = 'RETRIEVE_SCHEDULE_PICKUP_LIST_SUCCESS'
export const RETRIEVE_SCHEDULE_PICKUP_LIST_FAIL = 'RETRIEVE_SCHEDULE_PICKUP_LIST_FAIL'

export const RETRIEVE_SCHEDULE_PICKUP_DETAIL_REQUEST = 'RETRIEVE_SCHEDULE_PICKUP_DETAIL_REQUEST'
export const RETRIEVE_SCHEDULE_PICKUP_DETAIL_SUCCESS = 'RETRIEVE_SCHEDULE_PICKUP_DETAIL_SUCCESS'
export const RETRIEVE_SCHEDULE_PICKUP_DETAIL_FAIL = 'RETRIEVE_SCHEDULE_PICKUP_DETAIL_FAIL'

export const SCHEDULE_PICKUP_ADD_REQUEST = 'SCHEDULE_PICKUP_ADD_REQUEST'
export const SCHEDULE_PICKUP_ADD_SUCCESS = 'SCHEDULE_PICKUP_ADD_SUCCESS'
export const SCHEDULE_PICKUP_ADD_FAIL = 'SCHEDULE_PICKUP_ADD_FAIL'
export const SCHEDULE_PICKUP_ADD_RESET = 'SCHEDULE_PICKUP_ADD_RESET'

export const SCHEDULE_PICKUP_UPDATE_REQUEST = 'SCHEDULE_PICKUP_UPDATE_REQUEST'
export const SCHEDULE_PICKUP_UPDATE_SUCCESS = 'SCHEDULE_PICKUP_UPDATE_SUCCESS'
export const SCHEDULE_PICKUP_UPDATE_FAIL = 'SCHEDULE_PICKUP_UPDATE_FAIL'
export const SCHEDULE_PICKUP_UPDATE_RESET = 'SCHEDULE_PICKUP_UPDATE_RESET'

export const SCHEDULE_PICKUP_DISABLE_SUCCESS = 'SCHEDULE_PICKUP_DISABLE_SUCCESS'
export const SCHEDULE_PICKUP_DISABLE_FAIL = 'SCHEDULE_PICKUP_DISABLE_FAIL'
export const SCHEDULE_PICKUP_DISABLE_RESET = 'SCHEDULE_PICKUP_DISABLE_RESET'

export const SCHEDULE_PICKUP_DELETE_SUCCESS = 'SCHEDULE_PICKUP_DELETE_SUCCESS'
export const SCHEDULE_PICKUP_DELETE_FAIL = 'SCHEDULE_PICKUP_DELETE_FAIL'
export const SCHEDULE_PICKUP_DELETE_RESET = 'SCHEDULE_PICKUP_DELETE_RESET'