export const RETRIEVE_USER_LIST_REQUEST = 'RETRIEVE_USER_LIST_REQUEST'
export const RETRIEVE_USER_LIST_SUCCESS = 'RETRIEVE_USER_LIST_SUCCESS'
export const RETRIEVE_USER_LIST_FAIL = 'RETRIEVE_USER_LIST_FAIL'

export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'