export const RETRIEVE_USER_LIST_REQUEST = 'RETRIEVE_USER_LIST_REQUEST'
export const RETRIEVE_USER_LIST_SUCCESS = 'RETRIEVE_USER_LIST_SUCCESS'
export const RETRIEVE_USER_LIST_FAIL = 'RETRIEVE_USER_LIST_FAIL'

export const RETRIEVE_USER_DETAIL_REQUEST = 'RETRIEVE_USER_DETAIL_REQUEST'
export const RETRIEVE_USER_DETAIL_SUCCESS = 'RETRIEVE_USER_DETAIL_SUCCESS'
export const RETRIEVE_USER_DETAIL_FAIL = 'RETRIEVE_USER_DETAIL_FAIL'

export const RETRIEVE_USER_SCHEDULE_PICKUP_REQUEST = 'RETRIEVE_USER_SCHEDULE_PICKUP_REQUEST'
export const RETRIEVE_USER_SCHEDULE_PICKUP_SUCCESS = 'RETRIEVE_USER_SCHEDULE_PICKUP_SUCCESS'
export const RETRIEVE_USER_SCHEDULE_PICKUP_FAIL = 'RETRIEVE_USER_SCHEDULE_PICKUP_FAIL'

export const RETRIEVE_USER_SPECIAL_PICKUP_REQUEST = 'RETRIEVE_USER_SPECIAL_PICKUP_REQUEST'
export const RETRIEVE_USER_SPECIAL_PICKUP_SUCCESS = 'RETRIEVE_USER_SPECIAL_PICKUP_SUCCESS'
export const RETRIEVE_USER_SPECIAL_PICKUP_FAIL = 'RETRIEVE_USER_SPECIAL_PICKUP_FAIL'

export const USER_DETAIL_UPDATE_REQUEST = 'USER_DETAIL_UPDATE_REQUEST'
export const USER_DETAIL_UPDATE_SUCCESS = 'USER_DETAIL_UPDATE_SUCCESS'
export const USER_DETAIL_UPDATE_FAIL = 'USER_DETAIL_UPDATE_FAIL'
export const USER_DETAIL_UPDATE_RESET = 'USER_DETAIL_UPDATE_RESET'

export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'
export const USER_DELETE_RESET = 'USER_DELETE_RESET'