export const RETRIEVE_USER_LIST_REQUEST = 'RETRIEVE_USER_LIST_REQUEST'
export const RETRIEVE_USER_LIST_SUCCESS = 'RETRIEVE_USER_LIST_SUCCESS'
export const RETRIEVE_USER_LIST_FAIL = 'RETRIEVE_USER_LIST_FAIL'

export const RETRIEVE_ADMIN_DETAILS_REQUEST = 'RETRIEVE_ADMIN_DETAILS_REQUEST'
export const RETRIEVE_ADMIN_DETAILS_SUCCESS = 'RETRIEVE_ADMIN_DETAILS_SUCCESS'
export const RETRIEVE_ADMIN_DETAILS_FAIL = 'RETRIEVE_ADMIN_DETAILS_FAIL'

export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

export const ADMIN_DETAIL_UPDATE_REQUEST = 'ADMIN_DETAIL_UPDATE_REQUEST'
export const ADMIN_DETAIL_UPDATE_SUCCESS = 'ADMIN_DETAIL_UPDATE_SUCCESS'
export const ADMIN_DETAIL_UPDATE_FAIL = 'ADMIN_DETAIL_UPDATE_FAIL'
export const ADMIN_DETAIL_UPDATE_RESET = 'ADMIN_DETAIL_UPDATE_RESET'