export const GET_CONVERSATION_REQUEST = 'GET_CONVERSATION_REQUEST'
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATION_SUCCESS'
export const GET_CONVERSATION_FAIL = 'GET_CONVERSATION_FAIL'

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL'
export const SEND_MESSAGE_RESET = 'SEND_MESSAGE_RESET'

export const GET_ALL_CONVERSATIONS_REQUEST = 'GET_ALL_CONVERSATIONS_REQUEST'
export const GET_ALL_CONVERSATIONS_SUCCESS = 'GET_ALL_CONVERSATIONS_SUCCESS'
export const GET_ALL_CONVERSATIONS_FAIL = 'GET_ALL_CONVERSATIONS_FAIL'

export const UPDATE_READ_MESSAGE_SUCCESS = 'UPDATE_READ_MESSAGE_SUCCESS'
export const UPDATE_READ_MESSAGE_FAIL = 'UPDATE_READ_MESSAGE_FAIL'

export const ADD_CURRENT_CONVO = 'ADD_CURRENT_CONVO'
export const RESET_CURRENT_CONVO = 'RESET_CURRENT_CONVO'
export const ADD_CURRENT_CONVO_FAIL = 'ADD_CURRENT_CONVO_FAIL'

export const CONVERSATION_RECEIVED_SUCCESS = 'CONVERSATION_RECEIVED_SUCCESS'
export const CONVERSATION_RECEIVED_FAIL = 'CONVERSATION_RECEIVED_FAIL'