export const GET_CONVERSATION_REQUEST = 'GET_CONVERSATION_REQUEST'
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATION_SUCCESS'
export const GET_CONVERSATION_FAIL = 'GET_CONVERSATION_FAIL'
export const GET_CONVERSATION_RESET = 'GET_CONVERSATION_RESET'

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL'
export const SEND_MESSAGE_RESET = 'SEND_MESSAGE_RESET'

export const GET_MESSAGE_REQUEST = 'GET_MESSAGE_REQUEST'
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS'
export const GET_MESSAGE_FAIL = 'GET_MESSAGE_FAIL'
export const GET_MESSAGE_RESET = 'GET_MESSAGE_RESET'

export const GET_ALL_CONVERSATIONS_REQUEST = 'GET_ALL_CONVERSATIONS_REQUEST'
export const GET_ALL_CONVERSATIONS_SUCCESS = 'GET_ALL_CONVERSATIONS_SUCCESS'
export const GET_ALL_CONVERSATIONS_FAIL = 'GET_ALL_CONVERSATIONS_FAIL'