export const ADD_ORIGIN = 'ADD_ORIGIN'

export const ADD_LOCATION_REQUEST = 'ADD_LOCATION_REQUEST'
export const ADD_LOCATION_SUCCESS = 'ADD_LOCATION_SUCCESS'
export const ADD_LOCATION_FAIL = 'ADD_LOCATION_FAIL'

export const TASK_FETCH_LOCATION = 'TASK_FETCH_LOCATION'