export const PENDING_PICKUP_RETRIEVE_REQUEST = 'PENDING_PICKUP_RETRIEVE_REQUEST'
export const PENDING_PICKUP_RETRIEVE_SUCCESS = 'PENDING_PICKUP_RETRIEVE_SUCCESS'
export const PENDING_PICKUP_RETRIEVE_FAIL = 'PENDING_PICKUP_RETRIEVE_FAIL'

export const UPCOMING_PICKUP_RETRIEVE_REQUEST = 'UPCOMING_PICKUP_RETRIEVE_REQUEST'
export const UPCOMING_PICKUP_RETRIEVE_SUCCESS = 'UPCOMING_PICKUP_RETRIEVE_SUCCESS'
export const UPCOMING_PICKUP_RETRIEVE_FAIL = 'UPCOMING_PICKUP_RETRIEVE_FAIL'

export const COMPLETED_PICKUP_RETRIEVE_REQUEST = 'COMPLETED_PICKUP_RETRIEVE_REQUEST'
export const COMPLETED_PICKUP_RETRIEVE_SUCCESS = 'COMPLETED_PICKUP_RETRIEVE_SUCCESS'
export const COMPLETED_PICKUP_RETRIEVE_FAIL = 'COMPLETED_PICKUP_RETRIEVE_FAIL'

export const DECLINE_PICKUP_SUCCESS = 'DECLINE_PICKUP_SUCCESS'
export const DECLINE_PICKUP_FAIL = 'DECLINE_PICKUP_FAIL'

export const ACCEPT_PICKUP_SUCCESS = 'ACCEPT_PICKUP_SUCCESS'
export const ACCEPT_PICKUP_FAIL = 'ACCEPT_PICKUP_FAIL'

export const PICKUP_COMPLETED_SUCCESS = 'PICKUP_COMPLETED_SUCCESS'
export const PICKUP_COMPLETED_FAIL = 'PICKUP_COMPLETED_FAIL'