export const PENDING_PICKUP_RETRIEVE_REQUEST = 'PENDING_PICKUP_RETRIEVE_REQUEST'
export const PENDING_PICKUP_RETRIEVE_SUCCESS = 'PENDING_PICKUP_RETRIEVE_SUCCESS'
export const PENDING_PICKUP_RETRIEVE_FAIL = 'PENDING_PICKUP_RETRIEVE_FAIL'

export const UPCOMING_PICKUP_RETRIEVE_REQUEST = 'UPCOMING_PICKUP_RETRIEVE_REQUEST'
export const UPCOMING_PICKUP_RETRIEVE_SUCCESS = 'UPCOMING_PICKUP_RETRIEVE_SUCCESS'
export const UPCOMING_PICKUP_RETRIEVE_FAIL = 'UPCOMING_PICKUP_RETRIEVE_FAIL'

export const COMPLETED_PICKUP_RETRIEVE_REQUEST = 'COMPLETED_PICKUP_RETRIEVE_REQUEST'
export const COMPLETED_PICKUP_RETRIEVE_SUCCESS = 'COMPLETED_PICKUP_RETRIEVE_SUCCESS'
export const COMPLETED_PICKUP_RETRIEVE_FAIL = 'COMPLETED_PICKUP_RETRIEVE_FAIL'

export const PICKUP_COMPLETED_SUCCESS = 'PICKUP_COMPLETED_SUCCESS'
export const PICKUP_COMPLETED_FAIL = 'PICKUP_COMPLETED_FAIL'

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL'

export const ONGOING_PICKUP_ADD = 'ONGOING_PICKUP_ADD'
export const ONGOING_PICKUP_REMOVE = 'ONGOING_PICKUP_REMOVE'

export const SET_PICKUP_ACTIVE_SUCCESS = 'SET_PICKUP_ACTIVE_SUCCESS'
export const SET_PICKUP_ACTIVE_FAIL = 'SET_PICKUP_ACTIVE_FAIL'
