export const SPECIAL_PICKUP_ADD_REQUEST = 'SPECIAL_PICKUP_ADD_REQUEST'
export const SPECIAL_PICKUP_ADD_SUCCESS = 'SPECIAL_PICKUP_ADD_SUCCESS'
export const SPECIAL_PICKUP_ADD_FAIL = 'SPECIAL_PICKUP_ADD_FAIL'