export const PAYMENT_INTENT_REQUEST = 'PAYMENT_INTENT_REQUEST'
export const PAYMENT_INTENT_SUCCESS = 'PAYMENT_INTENT_SUCCESS'
export const PAYMENT_INTENT_FAIL = 'PAYMENT_INTENT_FAIL'

export const PAYMENT_SHEET_REQUEST = 'PAYMENT_SHEET_REQUEST'
export const PAYMENT_SHEET_SUCCESS = 'PAYMENT_SHEET_SUCCESS'
export const PAYMENT_SHEET_FAIL = 'PAYMENT_SHEET_FAIL'