export const SPECIAL_PICKUP_ADD_REQUEST = 'SPECIAL_PICKUP_ADD_REQUEST'
export const SPECIAL_PICKUP_ADD_SUCCESS = 'SPECIAL_PICKUP_ADD_SUCCESS'
export const SPECIAL_PICKUP_ADD_FAIL = 'SPECIAL_PICKUP_ADD_FAIL'
export const SPECIAL_PICKUP_STORE = 'SPECIAL_PICKUP_STORE'
export const SPECIAL_PICKUP_RESET = 'SPECIAL_PICKUP_RESET'

export const PICKUP_RETRIEVE_REQUEST = 'PICKUP_RETRIEVE_REQUEST'
export const PICKUP_RETRIEVE_SUCCESS = 'PICKUP_RETRIEVE_SUCCESS'
export const PICKUP_RETRIEVE_FAIL = 'PICKUP_RETRIEVE_FAIL'