export const SPECIAL_PICKUP_ADD_REQUEST = 'SPECIAL_PICKUP_ADD_REQUEST'
export const SPECIAL_PICKUP_ADD_SUCCESS = 'SPECIAL_PICKUP_ADD_SUCCESS'
export const SPECIAL_PICKUP_ADD_FAIL = 'SPECIAL_PICKUP_ADD_FAIL'
export const SPECIAL_PICKUP_STORE = 'SPECIAL_PICKUP_STORE'
export const SPECIAL_PICKUP_RESET = 'SPECIAL_PICKUP_RESET'

export const PENDING_PICKUP_RETRIEVE_REQUEST = 'PENDING_PICKUP_RETRIEVE_REQUEST'
export const PENDING_PICKUP_RETRIEVE_SUCCESS = 'PENDING_PICKUP_RETRIEVE_SUCCESS'
export const PENDING_PICKUP_RETRIEVE_FAIL = 'PENDING_PICKUP_RETRIEVE_FAIL'

export const ACCEPTED_PICKUP_RETRIEVE_REQUEST = 'ACCEPTED_PICKUP_RETRIEVE_REQUEST'
export const ACCEPTED_PICKUP_RETRIEVE_SUCCESS = 'ACCEPTED_PICKUP_RETRIEVE_SUCCESS'
export const ACCEPTED_PICKUP_RETRIEVE_FAIL = 'ACCEPTED_PICKUP_RETRIEVE_FAIL'

export const COMPLETED_PICKUP_RETRIEVE_REQUEST = 'COMPLETED_PICKUP_RETRIEVE_REQUEST'
export const COMPLETED_PICKUP_RETRIEVE_SUCCESS = 'COMPLETED_PICKUP_RETRIEVE_SUCCESS'
export const COMPLETED_PICKUP_RETRIEVE_FAIL = 'COMPLETED_PICKUP_RETRIEVE_FAIL'

export const ADD_SOCKET_SUCCESS = 'ADD_SOCKET_SUCCESS'
export const ADD_SOCKET_FAIL = 'ADD_SOCKET_FAIL'