export const SPECIAL_PICKUP_ADD_REQUEST = 'SPECIAL_PICKUP_ADD_REQUEST'
export const SPECIAL_PICKUP_ADD_SUCCESS = 'SPECIAL_PICKUP_ADD_SUCCESS'
export const SPECIAL_PICKUP_ADD_FAIL = 'SPECIAL_PICKUP_ADD_FAIL'
export const SPECIAL_PICKUP_STORE = 'SPECIAL_PICKUP_STORE'
export const SPECIAL_PICKUP_RESET = 'SPECIAL_PICKUP_RESET'

export const SCHEDULED_PICKUP_ADD_REQUEST = 'SCHEDULED_PICKUP_ADD_REQUEST'
export const SCHEDULED_PICKUP_ADD_SUCCESS = 'SCHEDULED_PICKUP_ADD_SUCCESS'
export const SCHEDULED_PICKUP_ADD_FAIL = 'SCHEDULED_PICKUP_ADD_FAIL'
export const SCHEDULED_PICKUP_STORE = 'SCHEDULED_PICKUP_STORE'
export const SCHEDULED_PICKUP_RESET = 'SCHEDULED_PICKUP_RESET'

export const PENDING_PICKUP_RETRIEVE_REQUEST = 'PENDING_PICKUP_RETRIEVE_REQUEST'
export const PENDING_PICKUP_RETRIEVE_SUCCESS = 'PENDING_PICKUP_RETRIEVE_SUCCESS'
export const PENDING_PICKUP_RETRIEVE_FAIL = 'PENDING_PICKUP_RETRIEVE_FAIL'

export const ACCEPTED_PICKUP_RETRIEVE_REQUEST = 'ACCEPTED_PICKUP_RETRIEVE_REQUEST'
export const ACCEPTED_PICKUP_RETRIEVE_SUCCESS = 'ACCEPTED_PICKUP_RETRIEVE_SUCCESS'
export const ACCEPTED_PICKUP_RETRIEVE_FAIL = 'ACCEPTED_PICKUP_RETRIEVE_FAIL'

export const COMPLETED_PICKUP_RETRIEVE_REQUEST = 'COMPLETED_PICKUP_RETRIEVE_REQUEST'
export const COMPLETED_PICKUP_RETRIEVE_SUCCESS = 'COMPLETED_PICKUP_RETRIEVE_SUCCESS'
export const COMPLETED_PICKUP_RETRIEVE_FAIL = 'COMPLETED_PICKUP_RETRIEVE_FAIL'

export const ADD_ONGOING_PICKUP_LOCATION = 'ADD_ONGOING_PICKUP_LOCATION'
export const REMOVE_ONGOING_PICKUP_LOCATION = 'REMOVE_ONGOING_PICKUP_LOCATION'

export const HIDE_COMPONENT_ADD = 'HIDE_COMPONENT_ADD'
export const HIDE_COMPONENT_REMOVE = 'HIDE_COMPONENT_REMOVE'