export const SCHEDULED_PICKUP_ADD_REQUEST = 'SCHEDULED_PICKUP_ADD_REQUEST'
export const SCHEDULED_PICKUP_ADD_SUCCESS = 'SCHEDULED_PICKUP_ADD_SUCCESS'
export const SCHEDULED_PICKUP_ADD_FAIL = 'SCHEDULED_PICKUP_ADD_FAIL'
export const SCHEDULED_PICKUP_STORE = 'SCHEDULED_PICKUP_STORE'
export const SCHEDULED_PICKUP_RESET = 'SCHEDULED_PICKUP_RESET'

export const SCHEDULED_PICKUP_RETRIEVE_REQUEST = 'SCHEDULED_PICKUP_RETRIEVE_REQUEST'
export const SCHEDULED_PICKUP_RETRIEVE_SUCCESS = 'SCHEDULED_PICKUP_RETRIEVE_SUCCESS'
export const SCHEDULED_PICKUP_RETRIEVE_FAIL = 'SCHEDULED_PICKUP_RETRIEVE_FAIL'